/// §11.5. The Drift database: schema, migrations and connection settings.
library;

import 'package:drift/drift.dart';

part 'database.g.dart';

/// §11.5. Zen's local database — one per replica (STORE-1).
///
/// The schema is declared in SQL under `tables/`, not in the Dart table DSL, so
/// that §11.5.2's constraints read as the specification writes them and
/// `drift_dev` validates every one at build time. Dart's `customConstraints`
/// would accept only constant literals and could not check them at all.
///
/// Everything §3.7 asks the persistence layer to enforce is here rather than in
/// the repositories: `CHECK` constraints for the single-row invariants, triggers
/// for INV-2 and INV-7, and partial unique indexes for NAME-6. §11.5.2 is
/// explicit about why — `zen_domain` guards its invariants with `assert`, which
/// Dart strips from release builds, so in the app you actually run these are
/// the only enforcement that executes.
@DriftDatabase(
  include: <String>{
    'tables/ideas.drift',
    'tables/tasks.drift',
    'tables/tags.drift',
    'tables/tombstones.drift',
    'tables/events.drift',
    'tables/replica.drift',
  },
)
class AppDatabase extends _$AppDatabase {
  /// Opens the database over [executor].
  AppDatabase(super.executor);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
    },
    // §11.5.3. There is no released version before this one, so there is no
    // upgrade to perform yet, and arriving here means the database came from a
    // build that no longer exists. Never edit a released migration; add a new
    // step to `schema_versions.dart` (regenerated by `drift_dev schema steps`)
    // and a new dump under `drift_schemas/`, and hand this over to
    // `stepByStep()`.
    onUpgrade: (Migrator m, int from, int to) async {
      throw UnsupportedError(
        'No migration from schema v$from to v$to exists. Schema v1 is the '
        'first released version (§11.5.3).',
      );
    },
    beforeOpen: (OpeningDetails details) async {
      // §11.5.5. Drift does not enable foreign keys by default, and the
      // `subtasks` and tag cascades depend on them. Must run outside a
      // transaction, which `customStatement` here does.
      await customStatement('PRAGMA foreign_keys = ON');
      // §11.5.5. WAL suits the read-heavy list screens alongside occasional
      // writes. It is a no-op for an in-memory database, which is why it is
      // not asserted here but in `connection.dart`'s file-backed path.
      await customStatement('PRAGMA journal_mode = WAL');
    },
  );
}
