// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Settings extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Settings(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> settingKey = GeneratedColumn<String>(
    'setting_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL PRIMARY KEY',
  );
  late final GeneratedColumn<String> settingValue = GeneratedColumn<String>(
    'setting_value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [settingKey, settingValue];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'settings';
  @override
  Set<GeneratedColumn> get $primaryKey => {settingKey};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Settings createAlias(String alias) {
    return Settings(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  bool get dontWriteConstraints => true;
}

class Replica extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Replica(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY',
  );
  late final GeneratedColumn<String> replicaId = GeneratedColumn<String>(
    'replica_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> deviceName = GeneratedColumn<String>(
    'device_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, replicaId, deviceName];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'replica';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Replica createAlias(String alias) {
    return Replica(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'CONSTRAINT single_row_replica CHECK(id = 1)',
    'CONSTRAINT replica_id_present CHECK(replica_id <> \'\')',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Events extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Events(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> eventId = GeneratedColumn<String>(
    'event_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL PRIMARY KEY',
  );
  late final GeneratedColumn<String> itemId = GeneratedColumn<String>(
    'item_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> itemKind = GeneratedColumn<String>(
    'item_kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> type = GeneratedColumn<String>(
    'type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> timestamp = GeneratedColumn<String>(
    'timestamp',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> payload = GeneratedColumn<String>(
    'payload',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'{}\'',
    defaultValue: const CustomExpression('\'{}\''),
  );
  @override
  List<GeneratedColumn> get $columns => [
    eventId,
    itemId,
    itemKind,
    type,
    timestamp,
    payload,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'events';
  @override
  Set<GeneratedColumn> get $primaryKey => {eventId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Events createAlias(String alias) {
    return Events(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'CONSTRAINT inv9_events_timestamp CHECK(length(timestamp) = 24 AND timestamp LIKE \'%Z\')',
    'CONSTRAINT item_kind_events CHECK(item_kind IN (\'idea\', \'task\'))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class IdeaTombstones extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  IdeaTombstones(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL PRIMARY KEY',
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> reason = GeneratedColumn<String>(
    'reason',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [id, deletedAt, reason];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'idea_tombstones';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  IdeaTombstones createAlias(String alias) {
    return IdeaTombstones(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'CONSTRAINT inv9_idea_tombstones_deleted_at CHECK(length(deleted_at) = 24 AND deleted_at LIKE \'%Z\')',
    'CONSTRAINT reason_idea_tombstones CHECK(reason IN (\'deleted\', \'converted\'))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Ideas extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Ideas(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL PRIMARY KEY',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> nameNormalized = GeneratedColumn<String>(
    'name_normalized',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> context = GeneratedColumn<String>(
    'context',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> timeframe = GeneratedColumn<String>(
    'timeframe',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    nameNormalized,
    context,
    timeframe,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'ideas';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Ideas createAlias(String alias) {
    return Ideas(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'CONSTRAINT inv5_ideas CHECK(created_at <= updated_at)',
    'CONSTRAINT inv9_ideas_created_at CHECK(length(created_at) = 24 AND created_at LIKE \'%Z\')',
    'CONSTRAINT inv9_ideas_updated_at CHECK(length(updated_at) = 24 AND updated_at LIKE \'%Z\')',
    'CONSTRAINT inv6_ideas_name CHECK(name <> \'\' AND name = trim(name) AND instr(name, char(10)) = 0 AND instr(name, char(13)) = 0 AND length(name) <= 16000)',
    'CONSTRAINT inv6_ideas_name_normalized CHECK(name_normalized <> \'\')',
    'CONSTRAINT inv6_ideas_context CHECK(length(context) <= 160000)',
    'CONSTRAINT timeframe_ideas CHECK(timeframe IN (\'now\', \'soon\', \'later\', \'distant\'))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class IdeaTags extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  IdeaTags(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES ideas(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
    'value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> valueNormalized = GeneratedColumn<String>(
    'value_normalized',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> sortIndex = GeneratedColumn<int>(
    'sort_index',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    ownerId,
    value,
    valueNormalized,
    sortIndex,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'idea_tags';
  @override
  Set<GeneratedColumn> get $primaryKey => {ownerId, valueNormalized};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {ownerId, sortIndex},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  IdeaTags createAlias(String alias) {
    return IdeaTags(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(owner_id, value_normalized)',
    'CONSTRAINT inv6_idea_tags_value CHECK(value <> \'\' AND instr(value, \' \') = 0 AND instr(value, char(9)) = 0 AND instr(value, char(10)) = 0 AND instr(value, char(13)) = 0 AND value NOT LIKE \'@%\' AND length(value) <= 512)',
    'CONSTRAINT inv6_idea_tags_value_normalized CHECK(value_normalized <> \'\')',
    'CONSTRAINT sort_index_idea_tags CHECK(sort_index >= 0)',
    'CONSTRAINT unique_idea_tags_order UNIQUE(owner_id, sort_index)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Tasks extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Tasks(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL PRIMARY KEY',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> nameNormalized = GeneratedColumn<String>(
    'name_normalized',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> description = GeneratedColumn<String>(
    'description',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> completedAt = GeneratedColumn<String>(
    'completed_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> isArchived = GeneratedColumn<int>(
    'is_archived',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> archivedAt = GeneratedColumn<String>(
    'archived_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> isDeleted = GeneratedColumn<int>(
    'is_deleted',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> deletedAt = GeneratedColumn<String>(
    'deleted_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> sourceIdeaId = GeneratedColumn<String>(
    'source_idea_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> sourceIdeaCreatedAt =
      GeneratedColumn<String>(
        'source_idea_created_at',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    nameNormalized,
    description,
    status,
    createdAt,
    updatedAt,
    completedAt,
    isArchived,
    archivedAt,
    isDeleted,
    deletedAt,
    sourceIdeaId,
    sourceIdeaCreatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'tasks';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Tasks createAlias(String alias) {
    return Tasks(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'CONSTRAINT inv1_tasks CHECK((status = \'done\')=(completed_at IS NOT NULL))',
    'CONSTRAINT inv3_tasks CHECK(is_archived = 0 OR status = \'done\')',
    'CONSTRAINT inv4_tasks_archived CHECK((is_archived = 1)=(archived_at IS NOT NULL))',
    'CONSTRAINT inv4_tasks_deleted CHECK((is_deleted = 1)=(deleted_at IS NOT NULL))',
    'CONSTRAINT inv5_tasks CHECK(created_at <= updated_at)',
    'CONSTRAINT inv8_tasks CHECK((source_idea_id IS NULL)=(source_idea_created_at IS NULL))',
    'CONSTRAINT inv9_tasks_created_at CHECK(length(created_at) = 24 AND created_at LIKE \'%Z\')',
    'CONSTRAINT inv9_tasks_updated_at CHECK(length(updated_at) = 24 AND updated_at LIKE \'%Z\')',
    'CONSTRAINT inv9_tasks_completed_at CHECK(completed_at IS NULL OR(length(completed_at) = 24 AND completed_at LIKE \'%Z\'))',
    'CONSTRAINT inv9_tasks_archived_at CHECK(archived_at IS NULL OR(length(archived_at) = 24 AND archived_at LIKE \'%Z\'))',
    'CONSTRAINT inv9_tasks_deleted_at CHECK(deleted_at IS NULL OR(length(deleted_at) = 24 AND deleted_at LIKE \'%Z\'))',
    'CONSTRAINT inv9_tasks_source_idea_created_at CHECK(source_idea_created_at IS NULL OR(length(source_idea_created_at) = 24 AND source_idea_created_at LIKE \'%Z\'))',
    'CONSTRAINT inv6_tasks_name CHECK(name <> \'\' AND name = trim(name) AND instr(name, char(10)) = 0 AND instr(name, char(13)) = 0 AND length(name) <= 16000)',
    'CONSTRAINT inv6_tasks_name_normalized CHECK(name_normalized <> \'\')',
    'CONSTRAINT inv6_tasks_description CHECK(length(description) <= 160000)',
    'CONSTRAINT status_tasks CHECK(status IN (\'todo\', \'blocked\', \'done\'))',
    'CONSTRAINT bool_tasks_is_archived CHECK(is_archived IN (0, 1))',
    'CONSTRAINT bool_tasks_is_deleted CHECK(is_deleted IN (0, 1))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class TaskTags extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TaskTags(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES tasks(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
    'value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> valueNormalized = GeneratedColumn<String>(
    'value_normalized',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> sortIndex = GeneratedColumn<int>(
    'sort_index',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    ownerId,
    value,
    valueNormalized,
    sortIndex,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'task_tags';
  @override
  Set<GeneratedColumn> get $primaryKey => {ownerId, valueNormalized};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {ownerId, sortIndex},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  TaskTags createAlias(String alias) {
    return TaskTags(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(owner_id, value_normalized)',
    'CONSTRAINT inv6_task_tags_value CHECK(value <> \'\' AND instr(value, \' \') = 0 AND instr(value, char(9)) = 0 AND instr(value, char(10)) = 0 AND instr(value, char(13)) = 0 AND value NOT LIKE \'@%\' AND length(value) <= 512)',
    'CONSTRAINT inv6_task_tags_value_normalized CHECK(value_normalized <> \'\')',
    'CONSTRAINT sort_index_task_tags CHECK(sort_index >= 0)',
    'CONSTRAINT unique_task_tags_order UNIQUE(owner_id, sort_index)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class Subtasks extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Subtasks(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL PRIMARY KEY',
  );
  late final GeneratedColumn<String> taskId = GeneratedColumn<String>(
    'task_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES tasks(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> sortIndex = GeneratedColumn<int>(
    'sort_index',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> createdAt = GeneratedColumn<String>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> updatedAt = GeneratedColumn<String>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> completedAt = GeneratedColumn<String>(
    'completed_at',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    taskId,
    name,
    status,
    sortIndex,
    createdAt,
    updatedAt,
    completedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'subtasks';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {taskId, sortIndex},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  Subtasks createAlias(String alias) {
    return Subtasks(attachedDatabase, alias);
  }

  @override
  bool get isStrict => true;
  @override
  List<String> get customConstraints => const [
    'CONSTRAINT inv1_subtasks CHECK((status = \'done\')=(completed_at IS NOT NULL))',
    'CONSTRAINT inv5_subtasks CHECK(created_at <= updated_at)',
    'CONSTRAINT inv9_subtasks_created_at CHECK(length(created_at) = 24 AND created_at LIKE \'%Z\')',
    'CONSTRAINT inv9_subtasks_updated_at CHECK(length(updated_at) = 24 AND updated_at LIKE \'%Z\')',
    'CONSTRAINT inv9_subtasks_completed_at CHECK(completed_at IS NULL OR(length(completed_at) = 24 AND completed_at LIKE \'%Z\'))',
    'CONSTRAINT inv6_subtasks_name CHECK(name <> \'\' AND name = trim(name) AND instr(name, char(10)) = 0 AND instr(name, char(13)) = 0 AND length(name) <= 16000)',
    'CONSTRAINT status_subtasks CHECK(status IN (\'todo\', \'blocked\', \'done\'))',
    'CONSTRAINT sort_index_subtasks CHECK(sort_index >= 0)',
    'CONSTRAINT unique_subtasks_order UNIQUE(task_id, sort_index)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final Settings settings = Settings(this);
  late final Replica replica = Replica(this);
  late final Events events = Events(this);
  late final Index idxEventsItem = Index(
    'idx_events_item',
    'CREATE INDEX idx_events_item ON events (item_id, timestamp)',
  );
  late final Index idxEventsTimestamp = Index(
    'idx_events_timestamp',
    'CREATE INDEX idx_events_timestamp ON events (timestamp)',
  );
  late final IdeaTombstones ideaTombstones = IdeaTombstones(this);
  late final Ideas ideas = Ideas(this);
  late final IdeaTags ideaTags = IdeaTags(this);
  late final Tasks tasks = Tasks(this);
  late final TaskTags taskTags = TaskTags(this);
  late final Index idxIdeaTagsNormalized = Index(
    'idx_idea_tags_normalized',
    'CREATE INDEX idx_idea_tags_normalized ON idea_tags (value_normalized)',
  );
  late final Index idxTaskTagsNormalized = Index(
    'idx_task_tags_normalized',
    'CREATE INDEX idx_task_tags_normalized ON task_tags (value_normalized)',
  );
  late final Index idxTasksActiveName = Index(
    'idx_tasks_active_name',
    'CREATE UNIQUE INDEX idx_tasks_active_name ON tasks (name_normalized) WHERE is_deleted = 0 AND is_archived = 0',
  );
  late final Index idxTasksActive = Index(
    'idx_tasks_active',
    'CREATE INDEX idx_tasks_active ON tasks (is_deleted, is_archived, created_at)',
  );
  late final Index idxTasksCompletedAt = Index(
    'idx_tasks_completed_at',
    'CREATE INDEX idx_tasks_completed_at ON tasks (completed_at)',
  );
  late final Subtasks subtasks = Subtasks(this);
  late final Index idxSubtasksTask = Index(
    'idx_subtasks_task',
    'CREATE INDEX idx_subtasks_task ON subtasks (task_id, sort_index)',
  );
  late final Trigger inv2SubtaskInsert = Trigger(
    'CREATE TRIGGER inv2_subtask_insert BEFORE INSERT ON subtasks WHEN NEW.status <> \'done\' AND (SELECT status FROM tasks WHERE id = NEW.task_id) = \'done\' BEGIN SELECT RAISE (ABORT, \'INV-2: a Done task cannot gain an open subtask\');END',
    'inv2_subtask_insert',
  );
  late final Trigger inv2SubtaskUpdate = Trigger(
    'CREATE TRIGGER inv2_subtask_update BEFORE UPDATE ON subtasks WHEN NEW.status <> \'done\' AND (SELECT status FROM tasks WHERE id = NEW.task_id) = \'done\' BEGIN SELECT RAISE (ABORT, \'INV-2: a Done task cannot hold an open subtask\');END',
    'inv2_subtask_update',
  );
  late final Trigger inv2TaskInsert = Trigger(
    'CREATE TRIGGER inv2_task_insert BEFORE INSERT ON tasks WHEN NEW.status = \'done\' AND EXISTS (SELECT 1 FROM subtasks WHERE task_id = NEW.id AND status <> \'done\') BEGIN SELECT RAISE (ABORT, \'INV-2: this task has subtasks that are not Done\');END',
    'inv2_task_insert',
  );
  late final Trigger inv2TaskUpdate = Trigger(
    'CREATE TRIGGER inv2_task_update BEFORE UPDATE ON tasks WHEN NEW.status = \'done\' AND EXISTS (SELECT 1 FROM subtasks WHERE task_id = NEW.id AND status <> \'done\') BEGIN SELECT RAISE (ABORT, \'INV-2: this task has subtasks that are not Done\');END',
    'inv2_task_update',
  );
  late final Index idxIdeasActiveName = Index(
    'idx_ideas_active_name',
    'CREATE UNIQUE INDEX idx_ideas_active_name ON ideas (name_normalized)',
  );
  late final Index idxIdeasCreatedAt = Index(
    'idx_ideas_created_at',
    'CREATE INDEX idx_ideas_created_at ON ideas (created_at)',
  );
  late final Trigger inv7IdeaInsert = Trigger(
    'CREATE TRIGGER inv7_idea_insert BEFORE INSERT ON ideas WHEN EXISTS (SELECT 1 FROM idea_tombstones WHERE id = NEW.id) BEGIN SELECT RAISE (ABORT, \'INV-7: this Idea id is tombstoned\');END',
    'inv7_idea_insert',
  );
  late final Trigger inv7IdeaUpdate = Trigger(
    'CREATE TRIGGER inv7_idea_update BEFORE UPDATE ON ideas WHEN EXISTS (SELECT 1 FROM idea_tombstones WHERE id = NEW.id) BEGIN SELECT RAISE (ABORT, \'INV-7: this Idea id is tombstoned\');END',
    'inv7_idea_update',
  );
  late final Trigger inv7TombstoneInsert = Trigger(
    'CREATE TRIGGER inv7_tombstone_insert BEFORE INSERT ON idea_tombstones WHEN EXISTS (SELECT 1 FROM ideas WHERE id = NEW.id) BEGIN SELECT RAISE (ABORT, \'INV-7: this Idea is still present; delete it first\');END',
    'inv7_tombstone_insert',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    settings,
    replica,
    events,
    idxEventsItem,
    idxEventsTimestamp,
    ideaTombstones,
    ideas,
    ideaTags,
    tasks,
    taskTags,
    idxIdeaTagsNormalized,
    idxTaskTagsNormalized,
    idxTasksActiveName,
    idxTasksActive,
    idxTasksCompletedAt,
    subtasks,
    idxSubtasksTask,
    inv2SubtaskInsert,
    inv2SubtaskUpdate,
    inv2TaskInsert,
    inv2TaskUpdate,
    idxIdeasActiveName,
    idxIdeasCreatedAt,
    inv7IdeaInsert,
    inv7IdeaUpdate,
    inv7TombstoneInsert,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'ideas',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('idea_tags', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'tasks',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('task_tags', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'tasks',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('subtasks', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'subtasks',
        limitUpdateKind: UpdateKind.insert,
      ),
      result: [],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'subtasks',
        limitUpdateKind: UpdateKind.update,
      ),
      result: [],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'tasks',
        limitUpdateKind: UpdateKind.insert,
      ),
      result: [],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'tasks',
        limitUpdateKind: UpdateKind.update,
      ),
      result: [],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'ideas',
        limitUpdateKind: UpdateKind.insert,
      ),
      result: [],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'ideas',
        limitUpdateKind: UpdateKind.update,
      ),
      result: [],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'idea_tombstones',
        limitUpdateKind: UpdateKind.insert,
      ),
      result: [],
    ),
  ]);
  @override
  int get schemaVersion => 1;
  @override
  DriftDatabaseOptions get options =>
      const DriftDatabaseOptions(storeDateTimeAsText: true);
}
