; Zen - Windows installer (ZEN_SPEC.md 11.9).
;
; Do not compile this by hand. `tools/package.ps1` builds the application first
; and passes every path and the version in as defines, so that the installer and
; the binaries inside it can never disagree about what release this is.
;
;   powershell -ExecutionPolicy Bypass -File tools\package.ps1
;
; See DECISIONS.md D-M8-4 for why the install is per-user and unsigned, and
; MANUAL_VERIFICATION.md section "M8" for the checklist this produces.

#ifndef AppVersion
  #error AppVersion is not defined. Run tools\package.ps1 rather than compiling this file directly.
#endif
#ifndef SourceDir
  #error SourceDir is not defined. Run tools\package.ps1 rather than compiling this file directly.
#endif
#ifndef RedistDir
  #error RedistDir is not defined. Run tools\package.ps1 rather than compiling this file directly.
#endif
#ifndef OutputDir
  #error OutputDir is not defined. Run tools\package.ps1 rather than compiling this file directly.
#endif

[Setup]
; ---------------------------------------------------------------------------
; ZEN_SPEC.md 11.9. THIS GUID IS THE PRODUCT'S IDENTITY AND MUST NEVER CHANGE.
;
; Inno Setup keys upgrade-in-place on AppId. A new GUID is, to Windows, a
; different product: installing it leaves the old Zen in place, so there are two
; entries in Apps & features and two copies on disk, and the one the Start menu
; points at is whichever wrote its shortcut last. This is the Windows
; counterpart to the Android signing keystore. It is recoverable -- uninstall
; the stray -- but it is the same class of mistake, so it is a literal here and
; is never regenerated by a tool or a wizard.
; ---------------------------------------------------------------------------
AppId={{EA883756-EE53-4C1C-AB9A-B5BCAEA79E5D}
AppName=Zen
AppVersion={#AppVersion}
AppVerName=Zen {#AppVersion}
VersionInfoVersion={#AppVersion}
AppPublisher=dev.zen
AppPublisherURL=
UninstallDisplayName=Zen
UninstallDisplayIcon={app}\zen_app.exe

; ZEN_SPEC.md 11.9: per-user. `lowest` means no UAC prompt, which matters for an
; unsigned binary that already draws a SmartScreen warning -- an elevation
; prompt on top of that is one more thing to click through and one less thing
; read. `{autopf}` resolves to %LOCALAPPDATA%\Programs under `lowest`. The data
; this manages is per-user anyway (see [UninstallDelete] below), so a
; machine-wide install would imply a sharing story the application does not have.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
DefaultDirName={autopf}\Zen
DefaultGroupName=Zen
DisableProgramGroupPage=yes
AllowNoIcons=yes

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0

OutputDir={#OutputDir}
OutputBaseFilename=Zen-{#AppVersion}-setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

; On an upgrade the previous Zen may be running. Inno detects the locked files
; and asks the user to close it, rather than killing a process that could be
; mid-sync.
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The whole Flutter release bundle: zen_app.exe, flutter_windows.dll, the
; plugin DLLs, sqlite3.dll and the data\ directory.
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; ZEN_SPEC.md 11.9. The Visual C++ runtime, app-local.
;
; The Flutter release bundle does not contain these, and a machine without the
; VC++ 2015-2022 redistributable fails to launch with a missing-DLL dialog that
; names nothing useful. The build machine always has the redistributable --
; installing the C++ toolchain puts it there -- so this failure appears only on
; the clean machine M8 is defined against, which is the one place it is never
; tried. Microsoft permits app-local deployment of these three; it costs about
; 700 KB and removes the failure mode entirely. Chaining VC_redist.x64.exe is
; the alternative and was rejected: ~25 MB and an elevation prompt, which would
; end the per-user install above.
Source: "{#RedistDir}\msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RedistDir}\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RedistDir}\vcruntime140_1.dll"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Zen"; Filename: "{app}\zen_app.exe"
Name: "{autodesktop}\Zen"; Filename: "{app}\zen_app.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\zen_app.exe"; Description: "{cm:LaunchProgram,Zen}"; Flags: nowait postinstall skipifsilent

; ---------------------------------------------------------------------------
; [UninstallDelete] IS DELIBERATELY ABSENT. DO NOT ADD ONE.
;
; ZEN_SPEC.md 11.9. The database, the pre-merge backups of 11.6.6 and the LAN
; pairing keys live in %APPDATA%\dev.zen\Zen -- outside {app}, because
; `path_provider_windows` builds that path from CompanyName and ProductName in
; windows\runner\Runner.rc. Inno removes only what it installed, so uninstalling
; already leaves the user's data alone. That is the correct behaviour, but it is
; currently the default rather than a decision, which is exactly how it gets
; broken: a single [UninstallDelete] entry added to "clean up properly" would
; destroy every Idea and Task, with no warning and no undo.
;
; For the same reason, CompanyName and ProductName in Runner.rc must not be
; edited. Changing either does not move the data; the application simply starts
; empty and the real database stays on disk where nothing looks for it.
; ---------------------------------------------------------------------------
